# Generated by Django 6.0.7 on 2026-08-11 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MemberRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150, verbose_name='Full name (as per ID/Baptism Card)')),
                ('national_id', models.CharField(max_length=30, verbose_name='National ID / Birth Certificate No.')),
                ('date_of_birth', models.DateField()),
                ('gender', models.CharField(choices=[('female', 'Female'), ('male', 'Male')], max_length=10)),
                ('marital_status', models.CharField(choices=[('single', 'Single'), ('married', 'Married'), ('other', 'Other')], default='single', max_length=10)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(db_index=True, max_length=254)),
                ('postal_address', models.CharField(blank=True, max_length=150)),
                ('residence', models.CharField(max_length=150, verbose_name='Residence (Estate/Village)')),
                ('occupation', models.CharField(max_length=150, verbose_name='Occupation / Student')),
                ('institution', models.CharField(blank=True, max_length=150, verbose_name='Institution (if student)')),
                ('parish', models.CharField(max_length=150, verbose_name='Church/Parish')),
                ('is_baptised', models.BooleanField(default=False, verbose_name='Baptism status')),
                ('is_confirmed', models.BooleanField(default=False, verbose_name='Confirmation status')),
                ('other_church_roles', models.CharField(blank=True, max_length=200)),
                ('date_of_joining', models.DateField(auto_now_add=True, verbose_name='Date of joining MKDY')),
                ('membership_category', models.CharField(choices=[('member', 'Member'), ('leader', 'Leader')], default='member', max_length=10)),
                ('next_of_kin_name', models.CharField(max_length=150)),
                ('next_of_kin_relationship', models.CharField(max_length=100)),
                ('next_of_kin_phone', models.CharField(max_length=20)),
                ('next_of_kin_alt_phone', models.CharField(blank=True, max_length=20)),
                ('status', models.CharField(choices=[('pending_payment', 'Pending Payment'), ('active', 'Active'), ('suspended', 'Suspended')], default='pending_payment', max_length=20)),
                ('membership_number', models.CharField(blank=True, max_length=30, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
